#!/usr/bin/env bash
#
# Renders Wear OS store screenshots from the :wear module via Paparazzi
# (layoutlib on the JVM — no emulator needed) and copies the generated PNGs to
# $SHOT_OUT. Run from app/android:
#
#   bash ../../scripts/wear-screenshots.sh
#
# `recordPaparazziDebug` writes images to wear/src/test/snapshots/images/;
# we flatten those into $SHOT_OUT. Best-effort: the CI step is
# continue-on-error, so a hiccup here only loses the wear shots.
set -uo pipefail

OUT="${SHOT_OUT:-$(pwd)/../build/screenshots/wear}"
mkdir -p "$OUT"

# Flutter gitignores the android gradle wrapper, so on a fresh CI checkout
# ./gradlew is absent (it's normally regenerated by the first flutter build).
# Regenerate it via Flutter's lightweight config-only pass.
if [ ! -x ./gradlew ]; then
  echo "wear-screenshots: gradle wrapper missing — generating via flutter"
  # Flutter injects the wrapper before invoking Gradle, so the wrapper appears
  # even if the config step itself errors out (e.g. on JDK mismatch). Don't gate
  # on the exit code — check that gradlew actually exists afterwards.
  ( cd .. && flutter build apk --config-only ) || true
fi
if [ ! -x ./gradlew ]; then
  echo "wear-screenshots: could not generate gradle wrapper — skipping" >&2
  exit 1
fi

echo "wear-screenshots: rendering Compose previews via Paparazzi …"
# -PwithPaparazzi applies the Paparazzi plugin (see wear/build.gradle.kts); it's
# left off for normal builds so release bundles don't depend on the alpha plugin.
./gradlew :wear:recordPaparazziDebug -PwithPaparazzi --no-daemon || {
  echo "wear-screenshots: gradle task failed — skipping" >&2
  exit 1
}

count=0
while IFS= read -r -d '' png; do
  cp "$png" "$OUT/$(basename "$png")"
  count=$((count + 1))
done < <(find wear/src/test/snapshots/images -name '*.png' -print0 2>/dev/null)

echo "wear-screenshots: copied $count screenshot(s) → $OUT"
[ "$count" -gt 0 ] || exit 1
